import "./globals.css";


export const mdaetata = {
  title: "ADV react",
  description: "Generated by me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
